---
apiVersion: /apps/v1
kind: Service
metadata:
  name: resultservice
  labels:
    type: webservice
    author: prapulla
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: resultapp
    author: prapulla
...