---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp
  labels:
    type: webapp
    author: prapulla
spec:
  replicas: 2
  selector:
    matchLabels:
      name: votingapp
  template:
    metadata:
      name: votingappPod
      labels:
        type: webapp
    spec:
      containers:
        - name: votingapp
          image: dockersamples/examplevotingapp_vote
...