---
apiVersion: /apps/v1
kind: Service
metadata:
  name: votingservice
  labels:
    type: webservice
    author: prapulla
spec:
  type: LoadBalancer
  ports:
    - targetPort:80
      port: 80
      nodePort: 30008
  selector:
    name: votingapp
    author: prapulla
...